# Copyright (c) 2025 Robert August Vincent II <pillarsdotnet@gmail.com>
# Co-author: Cursor-AI.
# See https://pre-commit.com for more information
default_language_version:
  node: "20"
repos:
  # commitlint: install with `pre-commit install --hook-type commit-msg`
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.24.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [markdown, yaml]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--fix]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [--shell=sh]
        files: ^(start|started|stop|timesheet|timeoff|install)$
