# Copyright (c) 2025 Robert August Vincent II <pillarsdotnet@gmail.com>
# Co-author: Cursor-AI.
# See https://prek.j178.dev for documentation.

default_language_version.node = "system"
default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "https://github.com/alessandrojcm/commitlint-pre-commit-hook"
rev = "v9.24.0"
hooks = [
  { id = "commitlint", stages = ["commit-msg"], additional_dependencies = ["@commitlint/config-conventional"] },
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-prettier"
rev = "v4.0.0-alpha.8"
hooks = [
  { id = "prettier", types_or = ["markdown", "yaml"] },
]

[[repos]]
repo = "https://github.com/igorshubovych/markdownlint-cli"
rev = "v0.39.0"
hooks = [
  { id = "markdownlint", args = ["--fix"] },
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "cargo-clippy",
    name = "cargo clippy",
    entry = "cargo clippy --all-targets -- -D warnings",
    language = "system",
    files = "\\.(rs|toml)$",
    pass_filenames = false,
  },
]
